#!/usr/bin/env python3
"""Generate deterministic synthetic vocabulary notes for demos and benchmarks."""

from __future__ import annotations

import argparse
from pathlib import Path


READING_INITIALS = tuple(
    "あいうえおかきくけこさしすせそたちつてとなにぬねの"
    "はひふへほまみむめもやゆよらりるれろわをん"
)


def render_note(index: int) -> str:
    initial = READING_INITIALS[index % len(READING_INITIALS)]
    reading = f"{initial}てすと"
    return (
        "---\n"
        f"reading: {reading}\n"
        "aliases:\n"
        f"  - synthetic-{index:06d}\n"
        "---\n\n"
        "Synthetic fixture generated by Kotoba Vault.\n"
    )


def generate(output: Path, count: int) -> None:
    if count < 1:
        raise ValueError("count must be at least 1")
    if output.exists() and any(output.iterdir()):
        raise FileExistsError(f"output directory is not empty: {output}")
    output.mkdir(parents=True, exist_ok=True)
    for index in range(count):
        path = output / f"synthetic-{index:06d}.md"
        path.write_text(render_note(index), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--count", type=int, default=1000)
    arguments = parser.parse_args()
    try:
        generate(arguments.output.resolve(), arguments.count)
    except (FileExistsError, ValueError) as error:
        parser.error(str(error))
    print(f"Generated {arguments.count} synthetic note(s) in {arguments.output}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
